# syntax=docker/dockerfile:experimental
FROM golang:1.14
    # set the workdir
    WORKDIR /go/src/app
    COPY . .

    # Download public key for github.com
    
    RUN mkdir -p -m 0600 ~/.ssh 
    RUN ssh-keyscan github.com >> ~/.ssh/known_hosts

    #RUN go get -d -v ./...
    #RUN go install -v ./...

    #RUN --mount=type=ssh git clone git@github.com:guther/guther.git myproject
   

 
